services:
  focusflow:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "${PORT:-3000}"
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
    volumes:
      - focusflow-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focusflow.rule=Host(`focusflow-3wzejs-db1293-152-53-52-156.traefik.me`)"
      - "traefik.http.routers.focusflow.entrypoints=websecure"
      - "traefik.http.routers.focusflow.tls=true"
      - "traefik.http.routers.focusflow.tls.certResolver=letsencrypt"
      - "traefik.http.services.focusflow.loadbalancer.server.port=3000"

volumes:
  focusflow-data:
    driver: local

networks:
  dokploy-network:
    external: true
