services:
  focusflow:
    build: .
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - focusflow-data:/app/data
      - ./prompts:/app/prompts:ro
    networks:
      - dokploy-gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3000/api/health',{cache:'no-store'}).then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  focusflow-data:

networks:
  dokploy-gateway:
    external: true
    name: gateway
