version: "3.9"

services:
  focusflow:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8080
    image: focusflow:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: 8080
      REFLEX_API_URL: http://localhost:8080
      REFLEX_REDIS_URL: redis://localhost
      FILES_DIR: /data/files
      DATABASE_URL: sqlite:////data/app.db
      # Pass through API keys from .env file
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
    volumes:
      - focusflow-data:/data
    restart: unless-stopped

volumes:
  focusflow-data:
    driver: local
