services:
  focusflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
    volumes:
      - focusflow-data:/data
    restart: unless-stopped

volumes:
  focusflow-data:
    driver: local